---
title: "First Look"
output: html_document
---

```{r setup, include=FALSE}
library("dplyr")
library('PerformanceAnalytics') #find correlation chart.Correlation()
library("ggplot2")
library("knitr")

#Read in the data()
med <- read.csv('~/Desktop/Demographic/claims_med_interns_2016-2018.csv')
pharm <- read.csv('~/Desktop/Demographic/claims_pharm_capstone_2016-2018.csv')

#med data analysis
print(colnames(med))
med_revise <- med %>% select("Claim.ID", "Member.Gender", "Age", "Zip..5.digit.", 
                         "Primary.ICD.Diagnosis.Code", "Primary.ICD.Rollup",
                         "Revenue.Code", "DRG.Code", "CCHG.Grouping", "CCHG.Label",
                         "Incurred.Year")
```

## Med Data Analysis
```{r, echo=FALSE}
#Gender Distribution
ggplot(med_revise) + 
  geom_histogram(aes(x=Member.Gender), stat="count") +
  labs(title = "Gender Distribution", x = "Gender", y = "Count")
```

```{r, echo=FALSE}
#Age Distribution
ggplot(med_revise) + 
  geom_histogram(aes(x=Age), stat="count") +
  labs(title = "Age Distribution", x = "Age", y = "Count")
```

```{r, echo=FALSE}
#Age Distribution by Year
ggplot(med_revise) + 
  geom_histogram(aes(x=Age), stat="count") +
  labs(title = "Age Distribution", x = "Age", y = "Count") +
  facet_wrap(~Incurred.Year)
```

```{r, echo=FALSE}
# Icd rollup distribution
icd <- med_revise %>% 
  group_by(Primary.ICD.Rollup) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(desc(n))
kable(icd[1:10,])
```

```{r, echo=FALSE}
# year counts
year <- med_revise %>% 
  group_by(Incurred.Year) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(desc(n))

ggplot(year) + 
  geom_bar(aes(x=Incurred.Year, y=n), stat="identity") +
  labs(title = "Year Counts", x = "Year", y = "Count")
```

```{r, echo=FALSE}
employee_type <- pharm %>% 
  group_by(Employee.Type) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(desc(n))

ggplot(employee_type) + 
  geom_bar(aes(x=Employee.Type, y=n), stat = "identity") +
  labs(title = "Employee Type Count", x = "Employee Type", y = "Count")
```

```{r, echo=FALSE}
#Chronic disease by gender
med_gender <- med_revise %>% 
  group_by(CCHG.Label, Member.Gender) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(CCHG.Label)

top_10 <- med_gender %>% arrange(desc(n))
kable(top_10[1:10,])
```

```{r, echo=FALSE}
#Chronic disease by age
med_age <- med_revise %>% 
  group_by(CCHG.Label, Age) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(CCHG.Label)

top_10 <- med_age %>% arrange(desc(n))
kable(top_10[1:10,])
```

```{r, echo=FALSE}
#Chronic disease by zipcode
med_zip <- med_revise %>% 
  group_by(CCHG.Label, Zip..5.digit.) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(CCHG.Label)

top_10 <- med_zip %>% arrange(desc(n))
kable(top_10[1:10,])
```

```{r, echo=FALSE}
#plot of 2016 Chronic disease by gender and age
med_analysis_2016 <- med_revise %>% 
  filter(Incurred.Year == 2016) %>% 
  group_by(CCHG.Label, Age, Member.Gender) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(CCHG.Label) %>% 
  ggplot() +
  geom_point(mapping = aes(x = Age, y = n, color = Member.Gender)) +
  facet_wrap(~CCHG.Label)

med_analysis_2016
```

```{r, echo=FALSE}
#plot of 2017 Chronic disease by gender and age
med_analysis_2017 <- med_revise %>% 
  filter(Incurred.Year == 2017) %>% 
  group_by(CCHG.Label, Age, Member.Gender) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(CCHG.Label) %>% 
  ggplot() +
  geom_point(mapping = aes(x = Age, y = n, color = Member.Gender)) +
  facet_wrap(~CCHG.Label)
med_analysis_2017
```

```{r, echo=FALSE}
#plot of 2018 Chronic disease by gender and age
med_analysis_2018 <- med_revise %>% 
  filter(Incurred.Year == 2018) %>% 
  group_by(CCHG.Label, Age, Member.Gender) %>% 
  distinct(Claim.ID) %>% 
  summarize(n=n()) %>% 
  arrange(CCHG.Label) %>% 
  ggplot() +
  geom_point(mapping = aes(x = Age, y = n, color = Member.Gender)) +
  facet_wrap(~CCHG.Label)
med_analysis_2018
```
